/**
 * Full World Cup Ball question bank — append new questions here (q26, q27, …).
 * Each quiz serves {@link WORLD_CUP_BALL_QUESTION_COUNT} questions picked from
 * ~{@link WORLD_CUP_BALL_COMBINATION_TARGET} pre-generated combinations.
 *
 * @type {Array<{ questionKey: string, prompt: string, acceptedAnswers: string[], choices?: string[], exclusionGroup?: string }>}
 */
export const WORLD_CUP_BALL_QUESTION_BANK = [
  {
    questionKey: 'q1',
    prompt: 'Who was the first African player to win the Ballon d’Or?',
    acceptedAnswers: ['George Weah', 'Weah', 'George Weah 1995', '1995'],
    exclusionGroup: 'george-weah',
  },
  {
    questionKey: 'q2',
    prompt:
      'In what year did Manchester United achieve the Treble (Premier League, FA Cup, Champions League)?',
    acceptedAnswers: ['1999', 'nineteen ninety nine', 'ninety nine'],
  },
  {
    questionKey: 'q3',
    prompt: 'Who holds the record for the most own goals in Premier League history?',
    acceptedAnswers: ['Richard Dunne', 'Dunne', 'Richard Dunne own goals'],
    exclusionGroup: 'richard-dunne',
  },
  {
    questionKey: 'q4',
    prompt: 'Which goalkeeper was the first to win the Ballon d’Or?',
    acceptedAnswers: ['Lev Yashin', 'Yashin', 'Lev Yashin 1963', '1963'],
    choices: ['Lev Yashin', 'Gianluigi Buffon', 'Manuel Neuer', 'Iker Casillas'],
    exclusionGroup: 'lev-yashin',
  },
  {
    questionKey: 'q5',
    prompt:
      'What was the exact scoreline of the 2005 Champions League Final between Liverpool and AC Milan before penalties?',
    acceptedAnswers: ['3-3', '3:3', '3 3', 'three three', '3–3'],
  },
  {
    questionKey: 'q6',
    prompt: 'Who scored the fastest hat-trick in Premier League history?',
    acceptedAnswers: [
      'Sadio Mané',
      'Sadio Mane',
      'Mane',
      'Mané',
      '2 minutes 56 seconds',
      '2 mins 56 secs',
      '2:56',
    ],
  },
  {
    questionKey: 'q7',
    prompt: 'Which player has scored the most goals in UEFA Champions League history?',
    acceptedAnswers: ['Cristiano Ronaldo', 'Ronaldo', 'C Ronaldo', 'CR7'],
    exclusionGroup: 'cristiano-ronaldo',
  },
  {
    questionKey: 'q8',
    prompt: 'Who was the first player to win the Premier League with two different clubs?',
    acceptedAnswers: ['Eric Cantona', 'Cantona'],
    exclusionGroup: 'eric-cantona',
  },
  {
    questionKey: 'q9',
    prompt: 'In which year did Cristiano Ronaldo win his first Ballon d’Or?',
    acceptedAnswers: ['2008'],
    choices: ['2008', '2007', '2009', '2016'],
    exclusionGroup: 'cristiano-ronaldo',
  },
  {
    questionKey: 'q10',
    prompt: 'Which manager has won the Champions League with three different clubs?',
    acceptedAnswers: ['Carlo Ancelotti', 'Ancelotti'],
  },
  {
    questionKey: 'q11',
    prompt: 'Which club has won the most UEFA Europa League titles (including the old UEFA Cup)?',
    acceptedAnswers: ['Sevilla', 'Sevilla 7', '7 titles', 'seven titles', '7'],
  },
  {
    questionKey: 'q12',
    prompt: 'Who scored the winning goal in the 1999 Champions League Final for Manchester United?',
    acceptedAnswers: [
      'Ole Gunnar Solskjær',
      'Ole Gunnar Solskjaer',
      'Solskjær',
      'Solskjaer',
    ],
  },
  {
    questionKey: 'q13',
    prompt: 'Which player has the most assists in Premier League history?',
    acceptedAnswers: ['Ryan Giggs', 'Giggs'],
    exclusionGroup: 'ryan-giggs',
  },
  {
    questionKey: 'q14',
    prompt: 'Who was the first non-European to win the Ballon d’Or?',
    acceptedAnswers: ['George Weah', 'Weah'],
    exclusionGroup: 'george-weah',
  },
  {
    questionKey: 'q15',
    prompt: 'What is the record for the most goals scored in a single Premier League season?',
    acceptedAnswers: [
      '32 goals',
      '32',
      'Mohamed Salah',
      'Erling Haaland',
      'Salah',
      'Haaland',
      'Salah and Haaland',
      'Haaland and Salah',
    ],
  },
  {
    questionKey: 'q16',
    prompt: 'Which English club has won the most European Cups / Champions League titles?',
    acceptedAnswers: ['Liverpool', 'Liverpool 6', '6 titles', '6', 'six titles'],
  },
  {
    questionKey: 'q17',
    prompt: 'Who is the youngest player to score in a Champions League final?',
    acceptedAnswers: ['Ansu Fati', 'Fati'],
  },
  {
    questionKey: 'q18',
    prompt: 'Which player has won the most Premier League titles?',
    acceptedAnswers: ['Ryan Giggs', 'Giggs', 'Ryan Giggs 13', '13 titles', '13'],
    exclusionGroup: 'ryan-giggs',
  },
  {
    questionKey: 'q19',
    prompt: 'Who scored the most goals in the 2014 World Cup?',
    acceptedAnswers: ['James Rodríguez', 'James Rodriguez', 'Rodriguez', 'Rodríguez'],
  },
  {
    questionKey: 'q20',
    prompt: 'Which team won the first ever Premier League title?',
    acceptedAnswers: [
      'Manchester United',
      'Man United',
      'Man Utd',
      'Manchester United 1992-93',
      '1992-93',
      '1992/93',
    ],
    exclusionGroup: 'man-utd-first-pl',
  },
  {
    questionKey: 'q21',
    prompt: 'Who is the all-time top scorer in the history of the England national team?',
    acceptedAnswers: ['Harry Kane', 'Kane'],
    exclusionGroup: 'harry-kane',
  },
  {
    questionKey: 'q22',
    prompt: 'Which player has the most appearances in the Premier League?',
    acceptedAnswers: ['Gareth Barry', 'Barry'],
  },
  {
    questionKey: 'q23',
    prompt: 'Who was the first player to score a hat-trick in a Champions League final?',
    acceptedAnswers: ['Pierino Prati', 'Prati', 'Pierino Prati 1969', '1969'],
  },
  {
    questionKey: 'q24',
    prompt: 'In which year did Liverpool win their first Champions League title?',
    acceptedAnswers: ['1977', 'nineteen seventy seven'],
  },
  {
    questionKey: 'q25',
    prompt: 'Which player is the only one to have won the Premier League Golden Boot with three different clubs?',
    acceptedAnswers: [
      'Jimmy Floyd Hasselbaink',
      'Hasselbaink',
      'Jimmy Hasselbaink',
      'Floyd Hasselbaink',
    ],
  },
  {
    questionKey: 'q26',
    prompt: 'Who has won the most Champions League titles as a player?',
    acceptedAnswers: ['Paco Gento', 'Gento', 'Francisco Gento', 'Paco Gento 6', '6 titles'],
    exclusionGroup: 'paco-gento-cl',
  },
  {
    questionKey: 'q27',
    prompt: 'Who was the first player to score in a Champions League final for two different clubs?',
    acceptedAnswers: ['Cristiano Ronaldo', 'Ronaldo', 'C Ronaldo', 'CR7'],
    exclusionGroup: 'cristiano-ronaldo',
  },
  {
    questionKey: 'q28',
    prompt: 'Which team holds the record for the longest unbeaten run in Premier League history?',
    acceptedAnswers: [
      'Arsenal',
      'Arsenal 49 games',
      '49 games',
      '2003-2004',
      '2003/2004',
      '2003–2004',
    ],
  },
  {
    questionKey: 'q29',
    prompt: 'Who is the only player to have won the Premier League, La Liga, and Serie A?',
    acceptedAnswers: ['David Beckham', 'Beckham'],
    exclusionGroup: 'david-beckham',
  },
  {
    questionKey: 'q30',
    prompt: 'In which year did England last win the FIFA World Cup?',
    acceptedAnswers: ['1966', 'nineteen sixty six'],
  },
  {
    questionKey: 'q31',
    prompt: 'Who scored the most goals in a single calendar year?',
    acceptedAnswers: ['Lionel Messi', 'Messi', '91 goals', '91', '2012'],
  },
  {
    questionKey: 'q32',
    prompt: 'Which manager has won the most Premier League titles?',
    acceptedAnswers: [
      'Sir Alex Ferguson',
      'Alex Ferguson',
      'Ferguson',
      '13 titles',
      '13',
    ],
  },
  {
    questionKey: 'q33',
    prompt: 'Who was the first non-British/Irish player to win the Premier League Golden Boot?',
    acceptedAnswers: ['Eric Cantona', 'Cantona'],
    exclusionGroup: 'eric-cantona',
  },
  {
    questionKey: 'q34',
    prompt: 'Which player has received the most red cards in Premier League history?',
    acceptedAnswers: ['Richard Dunne', 'Dunne'],
    exclusionGroup: 'richard-dunne',
  },
  {
    questionKey: 'q35',
    prompt: 'Who scored the fastest goal in a Champions League final?',
    acceptedAnswers: ['Paolo Maldini', 'Maldini', '51 seconds', '51 secs'],
  },
  {
    questionKey: 'q36',
    prompt: 'Which club has won the most consecutive UEFA Champions League titles?',
    acceptedAnswers: [
      'Real Madrid',
      'Real Madrid 5',
      '5 in a row',
      '1956-1960',
      '1956/1960',
      '1956–1960',
    ],
  },
  {
    questionKey: 'q37',
    prompt: 'Who is the only player to have scored in four different World Cup tournaments?',
    acceptedAnswers: ['Miroslav Klose', 'Klose'],
    exclusionGroup: 'four-world-cups-scorers',
  },
  {
    questionKey: 'q38',
    prompt: 'Who has the most caps for the England national team?',
    acceptedAnswers: ['Peter Shilton', 'Shilton', '125 caps', '125'],
  },
  {
    questionKey: 'q39',
    prompt: 'Who was the first player to win the Ballon d’Or while playing in the Premier League?',
    acceptedAnswers: ['Michael Owen', 'Owen', '2001'],
  },
  {
    questionKey: 'q40',
    prompt: 'Which team holds the record for the most consecutive clean sheets in the Premier League?',
    acceptedAnswers: ['Chelsea', 'Chelsea 2005', '2005'],
  },
  {
    questionKey: 'q41',
    prompt: 'Who was the top scorer at the 2018 FIFA World Cup?',
    acceptedAnswers: ['Harry Kane', 'Kane'],
    exclusionGroup: 'harry-kane',
  },
  {
    questionKey: 'q42',
    prompt: 'Which player has won the most FA Cup titles?',
    acceptedAnswers: ['Ryan Giggs', 'Giggs', '6', '6 titles'],
    exclusionGroup: 'ryan-giggs',
  },
  {
    questionKey: 'q43',
    prompt: 'Who is the only manager to have won the Premier League with two different clubs?',
    acceptedAnswers: ['Kenny Dalglish', 'Dalglish'],
    exclusionGroup: 'kenny-dalglish',
  },
  {
    questionKey: 'q44',
    prompt: 'Who has the most assists in UEFA Champions League history?',
    acceptedAnswers: ['Cristiano Ronaldo', 'Ronaldo', 'C Ronaldo', 'CR7'],
    exclusionGroup: 'cristiano-ronaldo',
  },
  {
    questionKey: 'q45',
    prompt: 'In which year did Leicester City win the Premier League title?',
    acceptedAnswers: ['2016', 'twenty sixteen'],
  },
  {
    questionKey: 'q46',
    prompt: 'Who was the first goalkeeper to score a goal in the Premier League?',
    acceptedAnswers: ['Peter Schmeichel', 'Schmeichel'],
  },
  {
    questionKey: 'q47',
    prompt: 'Which player has scored the most hat-tricks in Premier League history?',
    acceptedAnswers: ['Sergio Agüero', 'Sergio Aguero', 'Aguero', 'Agüero'],
  },
  {
    questionKey: 'q48',
    prompt: 'Who won the first ever Premier League Player of the Season award?',
    acceptedAnswers: ['Alan Shearer', 'Shearer', '1994/95', '1994-95'],
  },
  {
    questionKey: 'q49',
    prompt: 'Which team holds the record for the highest points total in a Premier League season?',
    acceptedAnswers: [
      'Manchester City',
      'Man City',
      '100 points',
      '100',
      '2017/18',
      '2017-18',
    ],
  },
  {
    questionKey: 'q50',
    prompt: 'Who is the only player to have won the UEFA Champions League with three different clubs?',
    acceptedAnswers: ['Clarence Seedorf', 'Seedorf'],
  },
  {
    questionKey: 'q51',
    prompt: 'Which country won the first FIFA World Cup in 1930?',
    acceptedAnswers: ['Uruguay'],
  },
  {
    questionKey: 'q52',
    prompt: 'Who captained Italy to victory at the 2006 FIFA World Cup?',
    acceptedAnswers: ['Fabio Cannavaro', 'Cannavaro'],
  },
  {
    questionKey: 'q53',
    prompt: 'Which nation hosted the 1962 FIFA World Cup?',
    acceptedAnswers: ['Chile'],
  },
  {
    questionKey: 'q54',
    prompt: 'Who scored the winning goal in the 2010 FIFA World Cup Final?',
    acceptedAnswers: ['Andrés Iniesta', 'Andres Iniesta', 'Iniesta'],
  },
  {
    questionKey: 'q55',
    prompt: 'Which goalkeeper has the most clean sheets in Premier League history?',
    acceptedAnswers: ['Petr Čech', 'Petr Cech', 'Cech', 'Čech'],
  },
  {
    questionKey: 'q56',
    prompt: 'In which stadium was the 1999 UEFA Champions League Final played?',
    acceptedAnswers: ['Camp Nou', 'Nou Camp'],
  },
  {
    questionKey: 'q57',
    prompt: 'Which player won the 1995 Ballon d’Or, becoming the first African winner?',
    acceptedAnswers: ['George Weah', 'Weah', 'George Weah 1995', '1995'],
    exclusionGroup: 'george-weah',
  },
  {
    questionKey: 'q58',
    prompt: 'Which club became the first English side to win the European Cup?',
    acceptedAnswers: ['Manchester United', 'Man United', 'Man Utd'],
  },
  {
    questionKey: 'q59',
    prompt:
      'Against which team did Sergio Agüero score Manchester City’s famous title-winning goal in 2012?',
    acceptedAnswers: [
      'Queens Park Rangers',
      'QPR',
      'Queens Park Rangers QPR',
    ],
  },
  {
    questionKey: 'q60',
    prompt: 'Which country finished third at the 2018 FIFA World Cup?',
    acceptedAnswers: ['Belgium'],
  },
  {
    questionKey: 'q61',
    prompt: 'Who managed Porto when they won the 2004 UEFA Champions League?',
    acceptedAnswers: ['José Mourinho', 'Jose Mourinho', 'Mourinho'],
    exclusionGroup: 'jose-mourinho',
  },
  {
    questionKey: 'q62',
    prompt: 'Which player scored the fastest goal in a FIFA World Cup Final?',
    acceptedAnswers: ['Johan Neeskens', 'Neeskens'],
  },
  {
    questionKey: 'q63',
    prompt: 'Which club did Zinedine Zidane leave before joining Real Madrid in 2001?',
    acceptedAnswers: ['Juventus'],
  },
  {
    questionKey: 'q64',
    prompt: 'Which nation hosted the 1978 FIFA World Cup?',
    acceptedAnswers: ['Argentina'],
  },
  {
    questionKey: 'q65',
    prompt:
      'Who scored Liverpool’s first goal in the 2005 Champions League Final comeback against AC Milan?',
    acceptedAnswers: ['Steven Gerrard', 'Gerrard'],
  },
  {
    questionKey: 'q66',
    prompt: 'Which team did Barcelona defeat in the 2009 UEFA Champions League Final?',
    acceptedAnswers: ['Manchester United', 'Man United', 'Man Utd'],
  },
  {
    questionKey: 'q67',
    prompt: 'Who was joint top scorer at the 1994 FIFA World Cup with six goals?',
    acceptedAnswers: [
      'Oleg Salenko and Hristo Stoichkov',
      'Salenko and Stoichkov',
      'Oleg Salenko',
      'Hristo Stoichkov',
      'Salenko',
      'Stoichkov',
    ],
  },
  {
    questionKey: 'q68',
    prompt: 'Which nation eliminated England on penalties in the quarter-finals of Euro 2004?',
    acceptedAnswers: ['Portugal'],
  },
  {
    questionKey: 'q69',
    prompt: 'Which player holds the record for the most assists in Premier League history?',
    acceptedAnswers: ['Ryan Giggs', 'Giggs'],
    exclusionGroup: 'ryan-giggs',
  },
  {
    questionKey: 'q70',
    prompt: 'In what year was the European Cup rebranded as the UEFA Champions League?',
    acceptedAnswers: ['1992'],
  },
  {
    questionKey: 'q71',
    prompt: 'Which nation won Euro 1992 despite not originally qualifying for the tournament?',
    acceptedAnswers: ['Denmark'],
  },
  {
    questionKey: 'q72',
    prompt: 'Who was the captain of Manchester United’s 1999 Treble-winning side?',
    acceptedAnswers: ['Roy Keane', 'Keane'],
  },
  {
    questionKey: 'q73',
    prompt: 'Which country hosted the 1986 FIFA World Cup?',
    acceptedAnswers: ['Mexico'],
  },
  {
    questionKey: 'q74',
    prompt: 'Who scored the winning penalty for Italy in the 2006 FIFA World Cup Final shootout?',
    acceptedAnswers: ['Fabio Grosso', 'Grosso'],
  },
  {
    questionKey: 'q75',
    prompt: 'Which club did Thierry Henry join directly after leaving Arsenal?',
    acceptedAnswers: ['Barcelona', 'FC Barcelona'],
  },
  {
    questionKey: 'q76',
    prompt: 'Which nation did Croatia defeat in the semi-finals to reach the 2018 World Cup Final?',
    acceptedAnswers: ['England'],
  },
  {
    questionKey: 'q77',
    prompt: 'Who was the first goalkeeper to win the Ballon d’Or?',
    acceptedAnswers: ['Lev Yashin', 'Yashin', 'Lev Yashin 1963', '1963'],
    exclusionGroup: 'lev-yashin',
  },
  {
    questionKey: 'q78',
    prompt: 'Which stadium hosted the 1966 FIFA World Cup Final?',
    acceptedAnswers: ['Wembley Stadium', 'Wembley', 'Old Wembley'],
  },
  {
    questionKey: 'q79',
    prompt: 'Who scored a hat-trick in the 1966 World Cup Final?',
    acceptedAnswers: ['Geoff Hurst', 'Hurst'],
    exclusionGroup: 'geoff-hurst-1966',
  },
  {
    questionKey: 'q80',
    prompt: 'Which club won the inaugural Premier League title in 1992–93?',
    acceptedAnswers: [
      'Manchester United',
      'Man United',
      'Man Utd',
      '1992-93',
      '1992/93',
    ],
    exclusionGroup: 'man-utd-first-pl',
  },
  {
    questionKey: 'q81',
    prompt: 'Who scored the winning goal in the 2014 FIFA World Cup Final?',
    acceptedAnswers: ['Mario Götze', 'Mario Gotze', 'Gotze', 'Götze'],
  },
  {
    questionKey: 'q82',
    prompt: 'Which country co-hosted Euro 2000 alongside Belgium?',
    acceptedAnswers: ['Netherlands', 'Holland'],
  },
  {
    questionKey: 'q83',
    prompt: 'Which player scored the famous “Hand of God” goal?',
    acceptedAnswers: ['Diego Maradona', 'Maradona'],
  },
  {
    questionKey: 'q84',
    prompt: 'Which club did Eric Cantona play for immediately before joining Manchester United?',
    acceptedAnswers: ['Leeds United', 'Leeds'],
    exclusionGroup: 'eric-cantona',
  },
  {
    questionKey: 'q85',
    prompt: 'Which nation won the first UEFA European Championship in 1960?',
    acceptedAnswers: ['Soviet Union', 'USSR', 'Soviet Union USSR'],
    exclusionGroup: 'euro-1960-winner',
  },
  {
    questionKey: 'q86',
    prompt: 'Who managed Greece when they won Euro 2004?',
    acceptedAnswers: ['Otto Rehhagel', 'Rehhagel'],
  },
  {
    questionKey: 'q87',
    prompt: 'Which club has won the most European Cups / Champions League titles?',
    acceptedAnswers: ['Real Madrid', 'Real Madrid 15', '15 titles'],
  },
  {
    questionKey: 'q88',
    prompt: 'Which goalkeeper captained Spain to victory at the 2010 FIFA World Cup?',
    acceptedAnswers: ['Iker Casillas', 'Casillas'],
  },
  {
    questionKey: 'q89',
    prompt: 'Which nation eliminated Brazil from the 2006 FIFA World Cup?',
    acceptedAnswers: ['France'],
  },
  {
    questionKey: 'q90',
    prompt:
      'Which goalkeeper made the decisive save in the 2008 Champions League Final penalty shootout?',
    acceptedAnswers: ['Edwin van der Sar', 'van der Sar', 'Van der Sar'],
  },
  {
    questionKey: 'q91',
    prompt: 'Which club did Luís Figo leave to join Real Madrid in 2000?',
    acceptedAnswers: ['Barcelona', 'FC Barcelona'],
  },
  {
    questionKey: 'q92',
    prompt: 'Which nation won the 1998 FIFA World Cup?',
    acceptedAnswers: ['France'],
  },
  {
    questionKey: 'q93',
    prompt: 'Who was the top scorer at the 2002 FIFA World Cup?',
    acceptedAnswers: [
      'Ronaldo',
      'Ronaldo Brazil',
      'Ronaldo Nazário',
      'Ronaldo Nazario',
      'R9',
    ],
    exclusionGroup: 'ronaldo-brazil',
  },
  {
    questionKey: 'q94',
    prompt: 'Which player has won the most FIFA World Cups as a player?',
    acceptedAnswers: ['Pelé', 'Pele'],
  },
  {
    questionKey: 'q95',
    prompt: 'Which club did Ronaldo Nazário join after leaving Inter Milan?',
    acceptedAnswers: ['Real Madrid'],
    exclusionGroup: 'ronaldo-brazil',
  },
  {
    questionKey: 'q96',
    prompt: 'Which nation finished as runners-up at the 1954 FIFA World Cup?',
    acceptedAnswers: ['Hungary'],
    exclusionGroup: 'hungary-1954-final',
  },
  {
    questionKey: 'q97',
    prompt: 'Who scored the opening goal of the 2018 FIFA World Cup?',
    acceptedAnswers: ['Yuri Gazinsky', 'Gazinsky', 'Yury Gazinsky'],
  },
  {
    questionKey: 'q98',
    prompt: 'Which manager won the Champions League with both Porto and Inter Milan?',
    acceptedAnswers: ['José Mourinho', 'Jose Mourinho', 'Mourinho'],
    exclusionGroup: 'jose-mourinho',
  },
  {
    questionKey: 'q99',
    prompt: 'Which country won the FIFA World Cup in 1974?',
    acceptedAnswers: ['West Germany', 'Germany', 'FRG'],
  },
  {
    questionKey: 'q100',
    prompt: 'Which player scored both goals for Brazil in the 2002 FIFA World Cup Final?',
    acceptedAnswers: [
      'Ronaldo',
      'Ronaldo Brazil',
      'Ronaldo Nazário',
      'Ronaldo Nazario',
      'R9',
    ],
    exclusionGroup: 'ronaldo-brazil',
  },
  {
    questionKey: 'q101',
    prompt: 'Which country won the 1950 FIFA World Cup?',
    acceptedAnswers: ['Uruguay'],
  },
  {
    questionKey: 'q102',
    prompt:
      'Who scored Germany’s seventh goal in the 7–1 victory over Brazil in the 2014 World Cup semi-final?',
    acceptedAnswers: ['Sami Khedira', 'Khedira'],
  },
  {
    questionKey: 'q103',
    prompt:
      'Which nation won the 2006 FIFA World Cup without conceding a goal in the knockout stage?',
    acceptedAnswers: ['Italy'],
  },
  {
    questionKey: 'q104',
    prompt: 'Which player won the Golden Ball at the 1998 FIFA World Cup?',
    acceptedAnswers: [
      'Ronaldo',
      'Ronaldo Brazil',
      'Ronaldo Nazário',
      'Ronaldo Nazario',
      'R9',
    ],
    exclusionGroup: 'ronaldo-brazil',
  },
  {
    questionKey: 'q105',
    prompt: 'Which countries hosted the first FIFA World Cup held in Asia?',
    acceptedAnswers: [
      'South Korea and Japan',
      'Japan and South Korea',
      'Korea and Japan',
      'Japan Korea',
      'South Korea Japan',
    ],
  },
  {
    questionKey: 'q106',
    prompt: 'Which nation defeated Argentina in the 1990 FIFA World Cup Final?',
    acceptedAnswers: ['West Germany', 'Germany', 'FRG'],
  },
  {
    questionKey: 'q107',
    prompt: 'Who scored the winning goal in the Euro 2000 Final?',
    acceptedAnswers: ['David Trezeguet', 'Trezeguet'],
  },
  {
    questionKey: 'q108',
    prompt: 'Which country won Euro 1988?',
    acceptedAnswers: ['Netherlands', 'Holland'],
  },
  {
    questionKey: 'q109',
    prompt: 'Who scored the “Golden Goal” that won Euro 1996 for Germany?',
    acceptedAnswers: ['Oliver Bierhoff', 'Bierhoff'],
  },
  {
    questionKey: 'q110',
    prompt: 'Which nation won the 2004 Copa América?',
    acceptedAnswers: ['Brazil'],
  },
  {
    questionKey: 'q111',
    prompt: 'Which club did AC Milan defeat in the 1994 Champions League Final?',
    acceptedAnswers: ['Barcelona', 'FC Barcelona'],
  },
  {
    questionKey: 'q112',
    prompt: 'Who scored the winning goal in the 2002 Champions League Final?',
    acceptedAnswers: ['Zinedine Zidane', 'Zidane'],
  },
  {
    questionKey: 'q113',
    prompt: 'Which club won the last European Cup before it was rebranded as the Champions League?',
    acceptedAnswers: ['Barcelona', 'FC Barcelona', '1992'],
  },
  {
    questionKey: 'q114',
    prompt: 'Which team defeated Bayern Munich in the 2012 Champions League Final?',
    acceptedAnswers: ['Chelsea'],
  },
  {
    questionKey: 'q115',
    prompt: 'Who was Chelsea’s manager when they won the 2012 Champions League?',
    acceptedAnswers: ['Roberto Di Matteo', 'Di Matteo', 'Roberto di Matteo'],
  },
  {
    questionKey: 'q116',
    prompt: 'Which club did Liverpool defeat in the 1984 European Cup Final?',
    acceptedAnswers: ['AS Roma', 'Roma'],
  },
  {
    questionKey: 'q117',
    prompt: 'Which club won the first UEFA Champions League title under the new format in 1993?',
    acceptedAnswers: ['Marseille', 'Olympique Marseille', 'OM'],
  },
  {
    questionKey: 'q118',
    prompt: 'Who scored Manchester United’s first goal in the 1999 Champions League Final?',
    acceptedAnswers: ['Teddy Sheringham', 'Sheringham'],
    exclusionGroup: 'teddy-sheringham-1999',
  },
  {
    questionKey: 'q119',
    prompt: 'Which club eliminated Barcelona in the semi-finals of the 2009–10 Champions League?',
    acceptedAnswers: ['Inter Milan', 'Inter', 'Internazionale'],
  },
  {
    questionKey: 'q120',
    prompt: 'Which goalkeeper captained Real Madrid to the 2014 Champions League title?',
    acceptedAnswers: ['Iker Casillas', 'Casillas'],
  },
  {
    questionKey: 'q121',
    prompt: 'Which player scored the first ever Premier League hat-trick?',
    acceptedAnswers: ['Eric Cantona', 'Cantona'],
    exclusionGroup: 'eric-cantona',
  },
  {
    questionKey: 'q122',
    prompt: 'Which club recorded the first “Invincible” Premier League season?',
    acceptedAnswers: ['Arsenal'],
  },
  {
    questionKey: 'q123',
    prompt: 'Who scored the most goals in the 1993–94 Premier League season?',
    acceptedAnswers: ['Andy Cole', 'Cole'],
  },
  {
    questionKey: 'q124',
    prompt: 'Which manager won the Premier League with Blackburn Rovers?',
    acceptedAnswers: ['Kenny Dalglish', 'Dalglish'],
    exclusionGroup: 'kenny-dalglish',
  },
  {
    questionKey: 'q125',
    prompt: 'Which club conceded only 15 goals during the 2004–05 Premier League season?',
    acceptedAnswers: ['Chelsea'],
  },
  {
    questionKey: 'q126',
    prompt: 'Who was Chelsea’s manager during the 2004–05 Premier League season?',
    acceptedAnswers: ['José Mourinho', 'Jose Mourinho', 'Mourinho'],
    exclusionGroup: 'jose-mourinho',
  },
  {
    questionKey: 'q127',
    prompt:
      'Which player scored the goal for Chelsea against Tottenham that meant Leicester City could no longer be caught in 2016?',
    acceptedAnswers: ['Eden Hazard', 'Hazard'],
  },
  {
    questionKey: 'q128',
    prompt: 'Which goalkeeper has made the most Premier League appearances?',
    acceptedAnswers: ['Mark Schwarzer', 'Schwarzer'],
  },
  {
    questionKey: 'q129',
    prompt:
      'Which club was the first Premier League champion from outside Manchester, London, or Liverpool?',
    acceptedAnswers: ['Blackburn Rovers', 'Blackburn'],
  },
  {
    questionKey: 'q130',
    prompt:
      'Which player won the Premier League Golden Boot three seasons in a row from 2013–14 to 2015–16?',
    acceptedAnswers: [
      'no one',
      'nobody',
      'none',
      'no player',
      'no',
      'not possible',
      'no such player',
      'trick question',
    ],
  },
  {
    questionKey: 'q131',
    prompt: 'Which club did Diego Maradona join after leaving Barcelona?',
    acceptedAnswers: ['Napoli'],
  },
  {
    questionKey: 'q132',
    prompt: 'Who was the first player to win three Ballon d’Or awards?',
    acceptedAnswers: ['Johan Cruyff', 'Cruyff'],
  },
  {
    questionKey: 'q133',
    prompt: 'Which country did Ferenc Puskás represent before later playing for Spain?',
    acceptedAnswers: ['Hungary'],
  },
  {
    questionKey: 'q134',
    prompt: 'Which stadium is known as “The Theatre of Dreams”?',
    acceptedAnswers: ['Old Trafford', 'Manchester United', 'Man United'],
    exclusionGroup: 'old-trafford-theatre',
  },
  {
    questionKey: 'q135',
    prompt: 'Who scored the winning goal in the 1974 FIFA World Cup Final?',
    acceptedAnswers: ['Gerd Müller', 'Gerd Muller', 'Muller', 'Müller'],
  },
  {
    questionKey: 'q136',
    prompt: 'Which club did Ronaldinho join after leaving Paris Saint-Germain?',
    acceptedAnswers: ['Barcelona', 'FC Barcelona'],
  },
  {
    questionKey: 'q137',
    prompt: 'Who was the first player to score in four different FIFA World Cup tournaments?',
    acceptedAnswers: ['Pelé', 'Pele'],
    exclusionGroup: 'four-world-cups-scorers',
  },
  {
    questionKey: 'q138',
    prompt: 'Which country did George Weah represent internationally?',
    acceptedAnswers: ['Liberia'],
    exclusionGroup: 'george-weah',
  },
  {
    questionKey: 'q139',
    prompt: 'Which player won the Golden Boot at the 1986 FIFA World Cup?',
    acceptedAnswers: ['Gary Lineker', 'Lineker'],
  },
  {
    questionKey: 'q140',
    prompt: 'Which manager led Argentina to the 1986 FIFA World Cup title?',
    acceptedAnswers: ['Carlos Bilardo', 'Bilardo'],
  },
  {
    questionKey: 'q141',
    prompt: 'Which nation was defeated by Spain in the final of Euro 2012?',
    acceptedAnswers: ['Italy'],
  },
  {
    questionKey: 'q142',
    prompt: 'Who scored the equalising goal for Manchester United in the 1999 Champions League Final?',
    acceptedAnswers: ['Teddy Sheringham', 'Sheringham'],
    exclusionGroup: 'teddy-sheringham-1999',
  },
  {
    questionKey: 'q143',
    prompt: 'Which club did Andrés Iniesta make his professional debut for?',
    acceptedAnswers: ['Barcelona', 'FC Barcelona'],
  },
  {
    questionKey: 'q144',
    prompt: 'Which country hosted Euro 1984?',
    acceptedAnswers: ['France'],
  },
  {
    questionKey: 'q145',
    prompt: 'Which player scored the winning penalty in the Euro 2020 Final shootout?',
    acceptedAnswers: [
      'Gianluigi Donnarumma',
      'Donnarumma',
      'no one',
      'nobody',
      'none',
      'no player',
      'no winning penalty',
      'save',
      'Saka miss',
      'Bukayo Saka miss',
      'Italy won on save',
    ],
  },
  {
    questionKey: 'q146',
    prompt:
      'Which club won the UEFA Cup in 2001 before becoming Champions League winners three years later?',
    acceptedAnswers: ['Porto'],
  },
  {
    questionKey: 'q147',
    prompt: 'Which player scored the only goal of the 1973 European Cup Final?',
    acceptedAnswers: ['Johnny Rep', 'Rep'],
  },
  {
    questionKey: 'q148',
    prompt: 'Which nation knocked holders France out of the 2002 FIFA World Cup?',
    acceptedAnswers: [
      'group stage',
      'eliminated in group stage',
      'Senegal',
      'Denmark',
      'Senegal and Denmark',
      'failed to win a match',
      'no wins',
      'France',
    ],
  },
  {
    questionKey: 'q149',
    prompt: 'Which goalkeeper won the Yashin Trophy in its inaugural year (2019)?',
    acceptedAnswers: [
      'Alisson Becker',
      'Alisson',
      'Alisson Becker Liverpool',
      'Becker',
    ],
  },
  {
    questionKey: 'q150',
    prompt: 'Which player scored the winning goal in the 1992 European Cup Final?',
    acceptedAnswers: ['Ronald Koeman', 'Koeman'],
  },
  {
    questionKey: 'q151',
    prompt: 'Which country won the FIFA World Cup in 1958?',
    acceptedAnswers: ['Brazil'],
  },
  {
    questionKey: 'q152',
    prompt: 'Who scored Brazil’s two goals in the 2002 FIFA World Cup Final?',
    acceptedAnswers: [
      'Ronaldo',
      'Ronaldo Brazil',
      'Ronaldo Nazário',
      'Ronaldo Nazario',
      'R9',
    ],
    exclusionGroup: 'ronaldo-brazil',
  },
  {
    questionKey: 'q153',
    prompt: 'Which club did Luís Suárez leave before joining Barcelona in 2014?',
    acceptedAnswers: ['Liverpool'],
  },
  {
    questionKey: 'q154',
    prompt: 'Who won the Ballon d’Or in 2007?',
    acceptedAnswers: ['Kaká', 'Kaka'],
  },
  {
    questionKey: 'q155',
    prompt: 'Which nation hosted the 1970 FIFA World Cup?',
    acceptedAnswers: ['Mexico'],
  },
  {
    questionKey: 'q156',
    prompt:
      'Who scored the decisive penalty in the shootout of the 1996 UEFA Champions League Final (after a 1–1 draw)?',
    acceptedAnswers: ['Vladimir Jugović', 'Vladimir Jugovic', 'Jugović', 'Jugovic'],
    choices: [
      'Vladimir Jugović',
      'Edgar Davids',
      'Alessandro Del Piero',
      'Jari Litmanen',
    ],
  },
  {
    questionKey: 'q157',
    prompt: 'Which country won the first UEFA European Championship, held in France in 1960?',
    acceptedAnswers: ['Soviet Union', 'USSR'],
    exclusionGroup: 'euro-1960-winner',
  },
  {
    questionKey: 'q158',
    prompt: 'Which club defeated Arsenal in the 2006 Champions League Final?',
    acceptedAnswers: ['Barcelona', 'FC Barcelona'],
  },
  {
    questionKey: 'q159',
    prompt: 'Who were joint top scorers at Euro 2000 with five goals each?',
    acceptedAnswers: [
      'Patrick Kluivert and Savo Milošević',
      'Kluivert and Milošević',
      'Patrick Kluivert and Savo Milosevic',
      'Kluivert and Milosevic',
      'Patrick Kluivert',
      'Savo Milošević',
      'Savo Milosevic',
    ],
    choices: [
      'Patrick Kluivert and Savo Milošević',
      'Patrick Kluivert',
      'Savo Milošević',
      'Alan Shearer and Thierry Henry',
    ],
  },
  {
    questionKey: 'q160',
    prompt: 'Which nation won the 1976 European Championship?',
    acceptedAnswers: ['Czechoslovakia', 'Czech Republic'],
  },
  {
    questionKey: 'q161',
    prompt: 'Who captained Germany to victory at the 2014 FIFA World Cup?',
    acceptedAnswers: ['Philipp Lahm', 'Lahm'],
    choices: ['Philipp Lahm', 'Manuel Neuer', 'Bastian Schweinsteiger', 'Miroslav Klose'],
  },
  {
    questionKey: 'q162',
    prompt: 'Which club did Gareth Bale leave to join Real Madrid?',
    acceptedAnswers: ['Tottenham Hotspur', 'Tottenham', 'Spurs'],
  },
  {
    questionKey: 'q163',
    prompt: 'Who scored the winning goal in the Euro 2016 Final?',
    acceptedAnswers: ['Éder', 'Eder'],
  },
  {
    questionKey: 'q164',
    prompt: 'Which nation reached the 1958 World Cup Final and lost to Brazil?',
    acceptedAnswers: ['Sweden'],
  },
  {
    questionKey: 'q165',
    prompt: 'Which club won the 1982 European Cup?',
    acceptedAnswers: ['Aston Villa', 'Villa'],
  },
  {
    questionKey: 'q166',
    prompt: 'Who managed France during their 1998 World Cup triumph?',
    acceptedAnswers: ['Aimé Jacquet', 'Aime Jacquet', 'Jacquet'],
  },
  {
    questionKey: 'q167',
    prompt: 'Which player won the Golden Ball at the 2014 FIFA World Cup?',
    acceptedAnswers: ['Lionel Messi', 'Messi'],
  },
  {
    questionKey: 'q168',
    prompt: 'Which nation hosted Euro 1988?',
    acceptedAnswers: ['West Germany', 'Germany', 'FRG'],
  },
  {
    questionKey: 'q169',
    prompt: 'Which club did Kaká join after leaving AC Milan in 2009?',
    acceptedAnswers: ['Real Madrid'],
  },
  {
    questionKey: 'q170',
    prompt: 'Who scored Porto’s opening goal in the 2004 Champions League Final?',
    acceptedAnswers: ['Carlos Alberto', 'Alberto'],
    choices: ['Carlos Alberto', 'Deco', 'Dmitri Alenichev', 'Maniche'],
  },
  {
    questionKey: 'q171',
    prompt: 'Which country won the FIFA World Cup in 1978?',
    acceptedAnswers: ['Argentina'],
  },
  {
    questionKey: 'q172',
    prompt: 'Which player scored the winning goal in the 1978 World Cup Final?',
    acceptedAnswers: ['Mario Kempes', 'Kempes'],
    exclusionGroup: 'mario-kempes-1978',
  },
  {
    questionKey: 'q173',
    prompt: 'Which club won the UEFA Cup Winners’ Cup in 1991?',
    acceptedAnswers: ['Manchester United', 'Man United', 'Man Utd'],
  },
  {
    questionKey: 'q174',
    prompt: 'Who was the top scorer at the 1998 FIFA World Cup?',
    acceptedAnswers: ['Davor Šuker', 'Davor Suker', 'Šuker', 'Suker'],
  },
  {
    questionKey: 'q175',
    prompt: 'Which nation defeated Italy in the final of Euro 2000?',
    acceptedAnswers: ['France'],
  },
  {
    questionKey: 'q176',
    prompt: 'Which club did Andrea Pirlo leave before joining Juventus?',
    acceptedAnswers: ['AC Milan', 'Milan'],
  },
  {
    questionKey: 'q177',
    prompt: 'Who scored the equaliser for Spain in the Euro 2008 Final?',
    acceptedAnswers: [
      'no one',
      'nobody',
      'none',
      'no equaliser',
      'Fernando Torres',
      'Torres',
      'Spain won 1-0',
      'Spain won 1–0',
      'No one — Spain won 1–0',
      'No one - Spain won 1-0',
    ],
    choices: [
      'No one — Spain won 1–0',
      'Fernando Torres',
      'David Villa',
      'Andrés Iniesta',
    ],
  },
  {
    questionKey: 'q178',
    prompt: 'Which country hosted the 1994 FIFA World Cup?',
    acceptedAnswers: ['United States', 'USA', 'US', 'America'],
  },
  {
    questionKey: 'q179',
    prompt: 'Which player won the Ballon d’Or in 1999?',
    acceptedAnswers: ['Rivaldo'],
  },
  {
    questionKey: 'q180',
    prompt: 'Which club won the first Champions League title of the 21st century?',
    acceptedAnswers: ['Bayern Munich', 'Bayern', 'Bayern München', '2001'],
    choices: ['Bayern Munich', 'Real Madrid', 'Manchester United', 'Valencia'],
  },
  {
    questionKey: 'q181',
    prompt: 'Which nation won the 1980 European Championship?',
    acceptedAnswers: ['West Germany', 'Germany', 'FRG'],
  },
  {
    questionKey: 'q182',
    prompt: 'Who scored France’s third goal in the 1998 World Cup Final?',
    acceptedAnswers: ['Emmanuel Petit', 'Petit'],
    choices: ['Emmanuel Petit', 'Zinedine Zidane', 'Youri Djorkaeff', 'Lilian Thuram'],
  },
  {
    questionKey: 'q183',
    prompt: 'Which club defeated Real Madrid in the 1983 European Cup Winners’ Cup Final?',
    acceptedAnswers: ['Aberdeen'],
  },
  {
    questionKey: 'q184',
    prompt: 'Who managed Aberdeen during their 1983 European Cup Winners’ Cup triumph?',
    acceptedAnswers: ['Sir Alex Ferguson', 'Alex Ferguson', 'Ferguson'],
  },
  {
    questionKey: 'q185',
    prompt: 'Which player scored the decisive penalty in the Euro 1976 Final shootout?',
    acceptedAnswers: ['Antonín Panenka', 'Antonin Panenka', 'Panenka'],
    choices: ['Antonín Panenka', 'Uli Hoeneß', 'Franz Beckenbauer', 'Sepp Maier'],
  },
  {
    questionKey: 'q186',
    prompt: 'Which country hosted the 1966 FIFA World Cup?',
    acceptedAnswers: ['England'],
  },
  {
    questionKey: 'q187',
    prompt: 'Which club did Xabi Alonso join after leaving Liverpool?',
    acceptedAnswers: ['Real Madrid'],
  },
  {
    questionKey: 'q188',
    prompt: 'Who was the top scorer at Euro 2012?',
    acceptedAnswers: ['Fernando Torres', 'Torres'],
  },
  {
    questionKey: 'q189',
    prompt: 'Which nation finished runners-up at the 2010 FIFA World Cup?',
    acceptedAnswers: ['Netherlands', 'Holland'],
  },
  {
    questionKey: 'q190',
    prompt: 'Which club won the 1987 European Cup?',
    acceptedAnswers: ['FC Porto', 'Porto'],
  },
  {
    questionKey: 'q191',
    prompt: 'Which player scored Porto’s famous backheel goal in the 1987 European Cup Final?',
    acceptedAnswers: ['Rabah Madjer', 'Madjer'],
    choices: ['Rabah Madjer', 'Juary', 'Jaime Magalhães', 'Sócrates'],
  },
  {
    questionKey: 'q192',
    prompt: 'Which nation won the FIFA World Cup in 1966?',
    acceptedAnswers: ['England'],
  },
  {
    questionKey: 'q193',
    prompt: 'Who won the Golden Boot at the 2010 FIFA World Cup?',
    acceptedAnswers: ['Thomas Müller', 'Thomas Muller', 'Muller', 'Müller'],
  },
  {
    questionKey: 'q194',
    prompt: 'Which club did Roberto Carlos leave before joining Real Madrid?',
    acceptedAnswers: ['Inter Milan', 'Inter'],
  },
  {
    questionKey: 'q195',
    prompt: 'Which country hosted Euro 1996?',
    acceptedAnswers: ['England'],
  },
  {
    questionKey: 'q196',
    prompt: 'Which player won the Ballon d’Or in 1987?',
    acceptedAnswers: ['Ruud Gullit', 'Gullit'],
  },
  {
    questionKey: 'q197',
    prompt: 'Which club won the European Cup in 1977?',
    acceptedAnswers: ['Liverpool'],
  },
  {
    questionKey: 'q198',
    prompt: 'Who scored Liverpool’s winning goal in the 1977 European Cup Final?',
    acceptedAnswers: ['Tommy Smith', 'Smith'],
    choices: ['Tommy Smith', 'Phil Neal', 'Terry McDermott', 'Kenny Dalglish'],
  },
  {
    questionKey: 'q199',
    prompt: 'Which nation defeated the Netherlands in the 2010 World Cup Final?',
    acceptedAnswers: ['Spain'],
  },
  {
    questionKey: 'q200',
    prompt: 'Which manager won the 1999 Champions League with Manchester United?',
    acceptedAnswers: ['Sir Alex Ferguson', 'Alex Ferguson', 'Ferguson'],
  },
  {
    questionKey: 'q201',
    prompt: 'Which country won the first FIFA Women’s World Cup in 1991?',
    acceptedAnswers: ['United States', 'USA', 'US', 'America'],
  },
  {
    questionKey: 'q202',
    prompt: 'Who scored the winning goal in the 1988 European Cup Final for PSV Eindhoven?',
    acceptedAnswers: [
      'no one',
      'nobody',
      'none',
      'no player',
      'penalties',
      '0-0',
      '0–0',
      'No one — match ended 0–0',
      'No one - match ended 0-0',
    ],
    choices: [
      'No one — match ended 0–0',
      'Ronald Koeman',
      'Anton Janssen',
      'Hans van Breukelen',
    ],
  },
  {
    questionKey: 'q203',
    prompt: 'Which club won the first UEFA Cup in 1972?',
    acceptedAnswers: ['Tottenham Hotspur', 'Tottenham', 'Spurs'],
  },
  {
    questionKey: 'q204',
    prompt: 'Who was the first English player to win the Ballon d’Or?',
    acceptedAnswers: ['Stanley Matthews', 'Matthews', 'Sir Stanley Matthews'],
    choices: ['Stanley Matthews', 'Bobby Charlton', 'Kevin Keegan', 'Gary Lineker'],
  },
  {
    questionKey: 'q205',
    prompt: 'Which nation won the 1964 European Championship?',
    acceptedAnswers: ['Spain'],
  },
  {
    questionKey: 'q206',
    prompt: 'Which club did Dennis Bergkamp join after leaving Inter Milan?',
    acceptedAnswers: ['Arsenal'],
  },
  {
    questionKey: 'q207',
    prompt: 'Who scored the winning goal in the 1980 European Championship Final?',
    acceptedAnswers: ['Horst Hrubesch', 'Hrubesch'],
  },
  {
    questionKey: 'q208',
    prompt: 'Which nation hosted the 1974 FIFA World Cup?',
    acceptedAnswers: ['West Germany', 'Germany', 'FRG'],
  },
  {
    questionKey: 'q209',
    prompt: 'Which club won the European Cup in 1968?',
    acceptedAnswers: ['Manchester United', 'Man United', 'Man Utd'],
  },
  {
    questionKey: 'q210',
    prompt: 'Who scored Manchester United’s second goal in the 1968 European Cup Final?',
    acceptedAnswers: ['George Best', 'Best'],
    choices: ['George Best', 'Bobby Charlton', 'Brian Kidd', 'Jaime Graça'],
    exclusionGroup: 'george-best',
  },
  {
    questionKey: 'q211',
    prompt: 'Which country won the FIFA World Cup in 1938?',
    acceptedAnswers: ['Italy'],
  },
  {
    questionKey: 'q212',
    prompt: 'Who was the top scorer at the 1978 FIFA World Cup?',
    acceptedAnswers: ['Mario Kempes', 'Kempes'],
    exclusionGroup: 'mario-kempes-1978',
  },
  {
    questionKey: 'q213',
    prompt: 'Which club did Ruud van Nistelrooy join after leaving Manchester United?',
    acceptedAnswers: ['Real Madrid'],
  },
  {
    questionKey: 'q214',
    prompt: 'Which nation finished runners-up at Euro 2004?',
    acceptedAnswers: ['Portugal'],
  },
  {
    questionKey: 'q215',
    prompt: 'Who won the Ballon d’Or in 1991?',
    acceptedAnswers: ['Jean-Pierre Papin', 'Papin', 'Jean Pierre Papin'],
  },
  {
    questionKey: 'q216',
    prompt: 'Which club won the UEFA Cup in 1980?',
    acceptedAnswers: ['Eintracht Frankfurt', 'Frankfurt'],
  },
  {
    questionKey: 'q217',
    prompt: 'Which nation won the 1972 European Championship?',
    acceptedAnswers: ['West Germany', 'Germany', 'FRG'],
  },
  {
    questionKey: 'q218',
    prompt: 'Who scored the winning goal in the 1972 European Championship Final?',
    acceptedAnswers: ['Gerd Müller', 'Gerd Muller', 'Muller', 'Müller'],
    choices: ['Gerd Müller', 'Franz Beckenbauer', 'Uli Hoeneß', 'Paul Breitner'],
  },
  {
    questionKey: 'q219',
    prompt: 'Which club defeated Real Madrid in the 1981 European Cup Final?',
    acceptedAnswers: ['Liverpool'],
  },
  {
    questionKey: 'q220',
    prompt: 'Who scored Liverpool’s goal in the 1981 European Cup Final?',
    acceptedAnswers: ['Alan Kennedy', 'Kennedy'],
    choices: ['Alan Kennedy', 'Kenny Dalglish', 'Graeme Souness', 'Phil Neal'],
  },
  {
    questionKey: 'q221',
    prompt: 'Which country hosted the 1958 FIFA World Cup?',
    acceptedAnswers: ['Sweden'],
  },
  {
    questionKey: 'q222',
    prompt: 'Which player won the Golden Ball at the 1982 FIFA World Cup?',
    acceptedAnswers: ['Paolo Rossi', 'Rossi'],
    choices: ['Paolo Rossi', 'Zico', 'Michel Platini', 'Dino Zoff'],
  },
  {
    questionKey: 'q223',
    prompt: 'Which club did Michael Ballack leave before joining Chelsea?',
    acceptedAnswers: ['Bayern Munich', 'Bayern', 'Bayern München'],
  },
  {
    questionKey: 'q224',
    prompt: 'Which nation won the Confederations Cup in 2009?',
    acceptedAnswers: ['Brazil'],
  },
  {
    questionKey: 'q225',
    prompt: 'Who was the top scorer at Euro 1996?',
    acceptedAnswers: ['Alan Shearer', 'Shearer'],
  },
  {
    questionKey: 'q226',
    prompt: 'Which club won the 1997 UEFA Champions League?',
    acceptedAnswers: ['Borussia Dortmund', 'Dortmund'],
  },
  {
    questionKey: 'q227',
    prompt: 'Which team did Borussia Dortmund defeat in the 1997 Champions League Final?',
    acceptedAnswers: ['Juventus'],
  },
  {
    questionKey: 'q228',
    prompt: 'Who scored twice for Borussia Dortmund in the 1997 Champions League Final?',
    acceptedAnswers: ['Karl-Heinz Riedle', 'Riedle', 'Karl Heinz Riedle'],
    choices: ['Karl-Heinz Riedle', 'Lars Ricken', 'Andreas Möller', 'Stéphane Chapuisat'],
  },
  {
    questionKey: 'q229',
    prompt: 'Which nation hosted Euro 1976?',
    acceptedAnswers: ['Yugoslavia'],
  },
  {
    questionKey: 'q230',
    prompt: 'Who won the Ballon d’Or in 1989?',
    acceptedAnswers: ['Marco van Basten', 'van Basten', 'Marco van Basten 1989'],
  },
  {
    questionKey: 'q231',
    prompt: 'Which country won the FIFA World Cup in 1934?',
    acceptedAnswers: ['Italy'],
  },
  {
    questionKey: 'q232',
    prompt: 'Which club did Clarence Seedorf join after leaving Real Madrid in 2000?',
    acceptedAnswers: ['Inter Milan', 'Inter'],
  },
  {
    questionKey: 'q233',
    prompt: 'Who was the top scorer at the 1990 FIFA World Cup?',
    acceptedAnswers: ['Salvatore Schillaci', 'Schillaci'],
  },
  {
    questionKey: 'q234',
    prompt: 'Which nation defeated Germany in the semi-finals of Euro 2016?',
    acceptedAnswers: ['France'],
  },
  {
    questionKey: 'q235',
    prompt: 'Which club won the European Cup Winners’ Cup in 1982?',
    acceptedAnswers: ['Barcelona', 'FC Barcelona'],
  },
  {
    questionKey: 'q236',
    prompt: 'Who scored Italy’s third goal in the 1982 World Cup Final?',
    acceptedAnswers: ['Alessandro Altobelli', 'Altobelli'],
    choices: ['Alessandro Altobelli', 'Marco Tardelli', 'Paolo Rossi', 'Antonio Cabrini'],
  },
  {
    questionKey: 'q237',
    prompt: 'Which nation hosted Euro 1992?',
    acceptedAnswers: ['Sweden'],
  },
  {
    questionKey: 'q238',
    prompt: 'Which player won the Ballon d’Or in 1985?',
    acceptedAnswers: ['Michel Platini', 'Platini'],
    exclusionGroup: 'michel-platini-ballon',
  },
  {
    questionKey: 'q239',
    prompt: 'Which club won the UEFA Cup in 1988?',
    acceptedAnswers: ['Bayer Leverkusen', 'Leverkusen'],
  },
  {
    questionKey: 'q240',
    prompt: 'Which country won the FIFA World Cup in 1954?',
    acceptedAnswers: ['West Germany', 'Germany', 'FRG'],
  },
  {
    questionKey: 'q241',
    prompt: 'Which nation did West Germany defeat in the 1954 World Cup Final?',
    acceptedAnswers: ['Hungary'],
    exclusionGroup: 'hungary-1954-final',
  },
  {
    questionKey: 'q242',
    prompt: 'Which club did Arjen Robben leave before joining Bayern Munich?',
    acceptedAnswers: ['Real Madrid'],
  },
  {
    questionKey: 'q243',
    prompt: 'Who won the Golden Boot at Euro 2004?',
    acceptedAnswers: ['Milan Baroš', 'Milan Baros', 'Baroš', 'Baros'],
  },
  {
    questionKey: 'q244',
    prompt: 'Which nation hosted the 1934 FIFA World Cup?',
    acceptedAnswers: ['Italy'],
  },
  {
    questionKey: 'q245',
    prompt: 'Which club won the 1986 European Cup?',
    acceptedAnswers: ['Steaua București', 'Steaua Bucharest', 'Steaua', 'Steaua Bucuresti'],
  },
  {
    questionKey: 'q246',
    prompt: 'Which team did Steaua București defeat in the 1986 European Cup Final?',
    acceptedAnswers: ['Barcelona', 'FC Barcelona'],
  },
  {
    questionKey: 'q247',
    prompt:
      'Who was the Steaua goalkeeper who saved all four Barcelona penalties in the 1986 European Cup Final shootout?',
    acceptedAnswers: [
      'Helmuth Duckadam',
      'Helmut Duckadam',
      'Duckadam',
    ],
    choices: [
      'Helmuth Duckadam',
      'Andoni Zubizarreta',
      'Francisco Buyo',
      'Uli Stein',
    ],
  },
  {
    questionKey: 'q248',
    prompt: 'Which nation won the 1968 European Championship?',
    acceptedAnswers: ['Italy'],
  },
  {
    questionKey: 'q249',
    prompt: 'Who won the Ballon d’Or in 1983?',
    acceptedAnswers: ['Michel Platini', 'Platini'],
    exclusionGroup: 'michel-platini-ballon',
  },
  {
    questionKey: 'q250',
    prompt: 'Which country finished third at the 1994 FIFA World Cup?',
    acceptedAnswers: ['Sweden'],
  },
  {
    questionKey: 'q251',
    prompt: 'Which club won the European Cup in 1970?',
    acceptedAnswers: ['Feyenoord'],
  },
  {
    questionKey: 'q252',
    prompt:
      'Which player famously said, “I spent a lot of money on booze, birds and fast cars. The rest I just squandered”?',
    acceptedAnswers: ['George Best', 'Best'],
    choices: ['George Best', 'Paul Gascoigne', 'Eric Cantona', 'George Weah'],
    exclusionGroup: 'george-best',
  },
  {
    questionKey: 'q253',
    prompt: 'Which club is nicknamed “The Old Lady”?',
    acceptedAnswers: ['Juventus'],
  },
  {
    questionKey: 'q254',
    prompt:
      'Which player was sent off in the 2006 World Cup Final for headbutting Marco Materazzi?',
    acceptedAnswers: ['Zinedine Zidane', 'Zidane'],
  },
  {
    questionKey: 'q255',
    prompt:
      'Which goalkeeper scored over 100 career goals, mostly from penalties and free kicks?',
    acceptedAnswers: [
      'Rogério Ceni',
      'Rogerio Ceni',
      'Ceni',
    ],
    choices: ['Rogério Ceni', 'José Luis Chilavert', 'René Higuita', 'Peter Schmeichel'],
  },
  {
    questionKey: 'q256',
    prompt: 'Which footballer was nicknamed “The Divine Ponytail”?',
    acceptedAnswers: ['Roberto Baggio', 'Baggio'],
    choices: ['Roberto Baggio', 'Francesco Totti', 'Alessandro Del Piero', 'Paolo Rossi'],
  },
  {
    questionKey: 'q257',
    prompt: 'Which club plays its home matches at La Bombonera?',
    acceptedAnswers: ['Boca Juniors', 'Boca'],
  },
  {
    questionKey: 'q258',
    prompt:
      'Which player scored five goals in nine minutes for Bayern Munich against Wolfsburg in 2015?',
    acceptedAnswers: ['Robert Lewandowski', 'Lewandowski'],
  },
  {
    questionKey: 'q259',
    prompt: 'Which manager coined the phrase “squeaky bum time”?',
    acceptedAnswers: ['Sir Alex Ferguson', 'Alex Ferguson', 'Ferguson'],
  },
  {
    questionKey: 'q260',
    prompt: 'Which country’s national team is nicknamed “The Oranje”?',
    acceptedAnswers: ['Netherlands', 'Holland'],
  },
  {
    questionKey: 'q261',
    prompt: 'Which player won league titles in England, Spain, Italy and Germany?',
    acceptedAnswers: ['David Beckham', 'Beckham'],
    exclusionGroup: 'david-beckham',
  },
  {
    questionKey: 'q262',
    prompt: 'Which club’s supporters are known as the “Yellow Wall”?',
    acceptedAnswers: ['Borussia Dortmund', 'Dortmund'],
  },
  {
    questionKey: 'q263',
    prompt: 'Which player scored the famous “Ghost Goal” in the 1966 World Cup Final?',
    acceptedAnswers: ['Geoff Hurst', 'Hurst'],
    exclusionGroup: 'geoff-hurst-1966',
  },
  {
    questionKey: 'q264',
    prompt: 'Which club did Eric Cantona describe as “the club of my heart” after retirement?',
    acceptedAnswers: ['Manchester United', 'Man United', 'Man Utd'],
    exclusionGroup: 'eric-cantona',
  },
  {
    questionKey: 'q265',
    prompt:
      'Which goalkeeper scored from his own penalty area in 2013 while playing for Stoke City?',
    acceptedAnswers: ['Asmir Begović', 'Asmir Begovic', 'Begović', 'Begovic'],
    choices: ['Asmir Begović', 'Tim Howard', 'Peter Schmeichel', 'Edwin van der Sar'],
    exclusionGroup: 'asmir-begovic-goal',
  },
  {
    questionKey: 'q266',
    prompt: 'Which country’s national team is nicknamed “The Red Fury”?',
    acceptedAnswers: ['Spain'],
  },
  {
    questionKey: 'q267',
    prompt: 'Which player has appeared in the most FIFA World Cup tournaments?',
    acceptedAnswers: [
      'Cristiano Ronaldo',
      'Ronaldo',
      'C Ronaldo',
      'CR7',
    ],
    choices: [
      'Cristiano Ronaldo',
      'Lionel Messi',
      'Lothar Matthäus',
      'Guillermo Ochoa',
    ],
    exclusionGroup: 'cristiano-ronaldo',
  },
  {
    questionKey: 'q268',
    prompt: 'Which football stadium is known as “The Cathedral of Football”?',
    acceptedAnswers: ['Wembley Stadium', 'Wembley', 'Old Wembley'],
  },
  {
    questionKey: 'q269',
    prompt: 'Which player won the Champions League with both Manchester United and Real Madrid?',
    acceptedAnswers: ['Cristiano Ronaldo', 'Ronaldo', 'C Ronaldo', 'CR7'],
    exclusionGroup: 'cristiano-ronaldo',
  },
  {
    questionKey: 'q270',
    prompt: 'Which manager won league titles in Portugal, England, Italy and Spain?',
    acceptedAnswers: ['José Mourinho', 'Jose Mourinho', 'Mourinho'],
    exclusionGroup: 'jose-mourinho',
  },
  {
    questionKey: 'q271',
    prompt: 'Which club’s nickname is “The Galácticos”?',
    acceptedAnswers: ['Real Madrid'],
  },
  {
    questionKey: 'q272',
    prompt:
      'Who missed England’s first penalty in the Euro 2004 quarter-final shootout against Portugal?',
    acceptedAnswers: ['David Beckham', 'Beckham'],
    choices: ['David Beckham', 'Darius Vassell', 'Wayne Rooney', 'Steven Gerrard'],
    exclusionGroup: 'david-beckham',
  },
  {
    questionKey: 'q273',
    prompt: 'Which country produced both Pelé and Garrincha?',
    acceptedAnswers: ['Brazil'],
  },
  {
    questionKey: 'q274',
    prompt:
      'Which player scored in FA Cup, League Cup and Champions League finals — and scored the winning penalty in Chelsea’s 2012 Champions League Final?',
    acceptedAnswers: ['Didier Drogba', 'Drogba'],
    choices: ['Didier Drogba', 'Frank Lampard', 'John Terry', 'Fernando Torres'],
  },
  {
    questionKey: 'q275',
    prompt: 'Which manager led Leicester City to the 2015–16 Premier League title?',
    acceptedAnswers: ['Claudio Ranieri', 'Ranieri'],
  },
  {
    questionKey: 'q276',
    prompt: 'Which club’s home stadium is nicknamed “The Theatre of Dreams”?',
    acceptedAnswers: ['Manchester United', 'Man United', 'Man Utd', 'Old Trafford'],
    exclusionGroup: 'old-trafford-theatre',
  },
  {
    questionKey: 'q277',
    prompt: 'Which player has won the most Champions League titles?',
    acceptedAnswers: ['Paco Gento', 'Gento', 'Francisco Gento'],
    choices: ['Paco Gento', 'Paolo Maldini', 'Cristiano Ronaldo', 'Lionel Messi'],
    exclusionGroup: 'paco-gento-cl',
  },
  {
    questionKey: 'q278',
    prompt: 'Which country’s fans are known for the Viking Clap?',
    acceptedAnswers: ['Iceland'],
  },
  {
    questionKey: 'q279',
    prompt: 'Which footballer was nicknamed “Il Fenomeno”?',
    acceptedAnswers: [
      'Ronaldo',
      'Ronaldo Nazário',
      'Ronaldo Nazario',
      'R9',
    ],
    choices: ['Ronaldo Nazário', 'Ronaldinho', 'Adriano', 'Romário'],
    exclusionGroup: 'ronaldo-brazil',
  },
  {
    questionKey: 'q280',
    prompt:
      'Which club won the Champions League despite finishing sixth in the Premier League that season?',
    acceptedAnswers: ['Chelsea', '2012', '2011-12', '2011/12'],
  },
  {
    questionKey: 'q281',
    prompt:
      'Which goalkeeper accidentally scored from his own penalty area while trying to clear the ball?',
    acceptedAnswers: ['Asmir Begović', 'Asmir Begovic', 'Begović', 'Begovic'],
    choices: ['Asmir Begović', 'Tim Howard', 'Peter Schmeichel', 'José Luis Chilavert'],
    exclusionGroup: 'asmir-begovic-goal',
  },
  {
    questionKey: 'q282',
    prompt: 'Which manager became famous for calling himself “The Special One”?',
    acceptedAnswers: ['José Mourinho', 'Jose Mourinho', 'Mourinho'],
    exclusionGroup: 'jose-mourinho',
  },
  {
    questionKey: 'q283',
    prompt: 'Which footballer celebrated a goal by pretending to fish with a corner flag?',
    acceptedAnswers: ['Paul Gascoigne', 'Gascoigne', 'Gazza'],
    choices: ['Paul Gascoigne', 'Peter Crouch', 'Eric Cantona', 'David Beckham'],
  },
  {
    questionKey: 'q284',
    prompt: 'Which player became famous for his robotic dance celebration?',
    acceptedAnswers: ['Peter Crouch', 'Crouch'],
  },
  {
    questionKey: 'q285',
    prompt:
      'Which striker once kicked a fan in the chest and still became a Manchester United legend?',
    acceptedAnswers: ['Eric Cantona', 'Cantona'],
    choices: ['Eric Cantona', 'Roy Keane', 'David Beckham', 'Wayne Rooney'],
    exclusionGroup: 'eric-cantona',
  },
  {
    questionKey: 'q286',
    prompt: 'Which footballer bit opponents at three different major clubs?',
    acceptedAnswers: ['Luis Suárez', 'Luis Suarez', 'Suárez', 'Suarez'],
    choices: ['Luis Suárez', 'Diego Costa', 'Zinedine Zidane', 'Eric Cantona'],
  },
  {
    questionKey: 'q287',
    prompt:
      'Which goalkeeper once scored a goal and then got sent off before the match ended?',
    acceptedAnswers: ['José Luis Chilavert', 'Jose Luis Chilavert', 'Chilavert'],
    choices: ['José Luis Chilavert', 'Rogério Ceni', 'René Higuita', 'Peter Schmeichel'],
  },
  {
    questionKey: 'q288',
    prompt:
      'Which manager famously sprinted down the touchline after a last-minute goal against Manchester United?',
    acceptedAnswers: ['José Mourinho', 'Jose Mourinho', 'Mourinho'],
    choices: ['José Mourinho', 'Sir Alex Ferguson', 'Pep Guardiola', 'Jürgen Klopp'],
    exclusionGroup: 'jose-mourinho',
  },
]
